version: '3.9'

services:
  server:
    container_name: 'server'
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - 'db'
  db:
    container_name: 'db'
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'docker'
    volumes:
      - 'data:/var/lib/postgresql/data'
  
volumes:
  data: