version: '3.9'

services:
  db:
    container_name: 'db'
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: 'docker'
      POSTGRES_USER: 'docker'
      POSTGRES_DB: 'pokkne-api'
    volumes:
      - 'data:/var/lib/postgresql/data'
  server:
    container_name: 'server'
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - 'db'

volumes:
  data: